ExternalProject_Add(libsoxr
    DEPENDS gcc
    URL "http://download.sourceforge.net/soxr/soxr-0.1.2-Source.tar.xz"
    URL_HASH SHA256=54e6f434f1c491388cd92f0e3c47f1ade082cc24327bdc43762f7d1eefe0c275
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DHAVE_WORDS_BIGENDIAN_EXITCODE=1
    BUILD_COMMAND ${CMAKE_MAKE_PROGRAM}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)
